APIHOST="https://api.factually.dev"
APIHOST="http://localhost:8080"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://www.who.int/emergencies/diseases/novel-coronavirus-2019\", \"rating\": 1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://www.who.int/news-room/q-a-detail/q-a-coronaviruses\", \"rating\": 1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://ec.europa.eu/info/live-work-travel-eu/health/coronavirus-response_en\", \"rating\": 1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://www.ecdc.europa.eu/en/covid-19-pandemic\", \"rating\": 1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://www.cdc.gov/coronavirus/2019-ncov/index.html\", \"rating\": 1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://www.visualcapitalist.com/history-of-pandemics-deadliest/\", \"rating\": 1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://multimedia.scmp.com/infographics/news/china/article/3075382/decoding-coronavirus-covid-19/index.html\", \"rating\": 1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://www.washingtonpost.com/graphics/2020/world/corona-simulator/\", \"rating\": 1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://www.visualcapitalist.com/infection-trajectory-flattening-the-covid19-curve/\", \"rating\": 1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://www.ft.com/coronavirus-latest\", \"rating\": 1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://ourworldindata.org/coronavirus\", \"rating\": 1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6\", \"rating\": 1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://covid19board.app\", \"rating\": 1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://covid.delabapps.eu/?fbclid=IwAR2Xv_FI4V_Z_X7-01bY_yNtlHkU_ni7po7wyrrp3o53E8qX1n01fceA-C0\", \"rating\": 1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://euvsdisinfo.eu/disinformation-cases/?text=coronavirus&date=\", \"rating\": 1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://ActivistPost.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://AmericanThinker.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://BeforeItsNews.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://BigLeaguePolitics.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Brighteon.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://BuffaloChronicle.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Collective-Evolution.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://DCClothesline.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://DCDirtyLaundry.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://DiamondandSilk.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://DoctorDavidFriedman.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://DrSergeGregoire.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://En-Volve.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://GNews.org\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://GreenMedInfo.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://HealingOracle.ch \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://HealthImpactNews.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://HealthNutNews.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Herbs-Info.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://HolisticHealth.one\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://HomeNaturalCures.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://HumansAreFree.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://InfoWars.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Intellihub.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://JimBakkerShow.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://JimHumble.co\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Medicine-Today.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Mercola.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://NaturalHealth365.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://NowTheEndBegins.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://NTDnews.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://OrganicConsumers.org\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://PrankMania.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Prntly.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://RealFarmacy.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://RedState.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://RedStateWatcher.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Reddit.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://RushLimbaugh.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://SonsOfLibertyMedia.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://SOTT.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://StopMandatoryVaccination.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://TechStartups.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://TheBL.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://TheDonald.win\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://TheEpochTimes.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://TheGatewayPundit.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://TheMindUnleashed.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://TheTruthAboutCancer.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://TierneyRealNewsNetwork.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Vaxxter.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://WakingTimes.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://WND.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://WorldHealth.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://WorldNewsDailyReport.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://ZeroHedge.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://4chan.org\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://8ch.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://NaturalNews.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Banned.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Biased.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Bioterrorism.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://CaliforniaCollapse.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://CDC.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Censorship.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Conspiracy.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Cures.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Depopulation.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Disinfo.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Eugenics.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Extinction.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://FactCheck.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Faked.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Freedom.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Health.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Herbs.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Honest.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Infections.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Journalism.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://MediaFactWatch.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://MedicalExtremism.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Medicine.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://NaturalCures.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://NaturalNewsRadio.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Naturopathy.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://NewsFakes.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://NewsTarget.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://NYTWatch.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://OpenBorders.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Outbreak.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Pandemic.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Panic.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://PlantMedicine.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://PopulationControl.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Propaganda.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://RealInvestigations.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Remedies.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Risk.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://ScienceClowns.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://ScienceFraud.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Science.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Scientific.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Sheeple.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://SHTF.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Superbugs.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://TechGiants.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Technocrats.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Twisted.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Tyranny.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Uprising.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://VaccineDamage.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://VaccineInjuryNews.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Vaccines.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://WaPoop.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://WashingtonPosted.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Now8News.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Breaking13News.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://AlterInfo.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://AubeDigitale.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Cogiito.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://EgaliteEtReconciliation.fr\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://EpochTimes.fr\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Fawkes-News.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://FL24.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Fr.SputnikNews.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://French.PressTV.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://LesMoutonsEnrages.fr\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://LesMoutonsRebelles.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://LumiereSurGaia.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Medias-Presse.info\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://NoSignalFound.fr\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://NouvelOrdremondial.cc\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://NS2017.Wordpress.com \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Panamza.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Patriote.Info\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://ReseauInternational.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://ResistanceRepublicaine.eu\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://RiposteLaique.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Wikistrike.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://ByoBlu.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://CaffeinaMagazine.it\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Corvelva.it\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Disinformazione.it\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://FonteVerificata.it\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://GospaNews.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://IlPopulista.it\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://IlPrimatoNazionale.it\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://ImolaOggi.it\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://It.SputnikNews.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://LaVoceDelTrentino.it\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Leggilo.org\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://MaurizioBlondet.it\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://MedNat.org\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://PandoraTv.it\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Renovatio21.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://ScenariEconomici.it\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://SegniDalCielo.it\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://StefanoMontanari.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://StopCensura.info\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Tgcom24.mediaset.it\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://ViralMagazine.it\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://VoxNews.info\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Altermedzentrum.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://AnonymousNews.ru\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Compact-Online.de\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Connectiv.events\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Contra-Magazin.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://De.News-Front.info\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://De.SputnikNews.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Deutsch.RT.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Deutschland-Kurier.org\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Indexexpurgatorius.wordpress.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://JournalistenWatch.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Kla.tv\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Liebeisstleben.de\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://MariaLourdesBlog.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Medizin-Heute.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://N23.tv\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://News-for-Friends.de\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Politikstube.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://PolitikVersagen.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Pravda-TV.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://ScienceFiles.org  \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Snap4Face.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Watergate.tv\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://GlobalResearch.ca\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://GreatGameIndia.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Mondialisation.ca\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://24Jours.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Factuel.afp.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Journal-neo.org\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Otsm.pl\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Oneworld.press\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Es.news-front.info\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Utro.ru\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Fort-russ.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Arabic.rt.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Riafan.ru\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Antifashist.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://albayan.ae \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://sarayanews.com \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://hakaekonline.com \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://afaq.tv\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://nabd.com \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://aljaras.com \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://paltimesps.ps \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://mz-mz.net,\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://samanews.ps \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://al-marsd.com \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://alwehda.gov.sy \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://alasmeh.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://almarrakchia.net \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://menafn.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://turkeyalaan.net \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://gulf365.co\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://yemeninews.net \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://newyork-news.us \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://factjo.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://yemennownews.com \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://alaraby-media.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://sahafahnews.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://arabstoday.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://khaberni.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://znobia.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://albalqatoday.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://turess.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://sahafah-24.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://elwassat.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://sahafahnet.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://betalshames.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://alkhabar-sy.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://haolalaalam24.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://samapress.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://timesofps.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://garaanews.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://alsahifa.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://yementime.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://akhbarak.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://sourpress.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://nabdapp.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://ksa-wats.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://assukari-news.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://shaamtimes.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://alhadeel.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Mediaelbalad.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://sawahpress.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://hiwaralssaea.com \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://yemenvibe.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://6060news.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://sanaanews.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://laracheinfo.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://sudafax.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://blanklytalk.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://maghress.com, sinmarnews.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://masralyoum.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://albousla.ps\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://khafayalb.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://klyoum.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://rjeem.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://albidda.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://khabr.online\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://46-105-42-7.ovh.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://ahlmasrnews.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://akherkhabaronline.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://ammarjohmani.blogspot.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://saadaonline.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://hamsaat.co\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://watan.news \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://lomazoma.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://skywaterjo.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://khabarlb.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://rtarab.com, \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://wasatt.org, \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://opinyatimes.com, \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://emiratesvoice.com, \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://msdernet.xyz, \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://sst.sy, \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://syria-24.com, \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://doniaalyoum.com, \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://emaratyah.ae, \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://jpsyria.net, \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://alazmenah.com, \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://sudaneseonline.com, \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://kol-masr.com, \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://almaghribtoday.net, \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://khbrpress.ps, \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://jpnews-sy.com, \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://ar.rt.com, \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://news.dmcnews.org, \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://mapress.net, \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://pressbee.net, \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://sportnewsps.com, \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://theworldnews.net, \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://eshraag.com, \", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://sahafahn.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Wolna-polska.pl\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://alternews.pl\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://alexjones.pl\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://dziennik-polityczny.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://hnews.pl\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://koniec-swiata.org\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://magnapolonia.org\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://narodowcy.net\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://nczas.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://ndie.pl\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://neon24.pl\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://newsweb.pl\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://parezja.pl\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://pikio.pl\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://prostozmostu24.pl\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://prawdaobiektywna.pl\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://reporters.pl\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://sioe.pl\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://wmeritum.pl\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://wolnosc24.pl\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://wprawo.pl\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://wsensie.pl\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Zmianynaziemi.pl\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Geopolitica.ru\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Sputnik.by\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Iravunk.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Business-gazeta.ru\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Hu.news-front.info\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Oneworld.press\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://ukrlife.tv\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://ryszardpiotrnisza.blogspot.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Ukraina.ru\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Rg.ru\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Fondsk.ru\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://ar.rt.com/nmnv\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://al-vefagh.com/News/279277.html\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://De.sputniknews.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Al-vefagh.com\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://Alwafd.news\", \"rating\": -1}"
curl -X POST "${APIHOST}/insert" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"apiKey\": \"${APIKEY}\", \"url\": \"https://\", \"rating\": -1}"
